title: myblog
baseurl: ""
url: "https://sesseljabs.github.io/curly-website/"

defaults:
  - scope:
      path: "/curly-website/"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/curly-website/"
    values:
      layout: "default"